# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1280, 720))
        MainWindow.setMaximumSize(QSize(1280, 720))
        MainWindow.setBaseSize(QSize(1280, 720))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setStyleSheet(u"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 20))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolDock = QDockWidget(MainWindow)
        self.toolDock.setObjectName(u"toolDock")
        sizePolicy.setHeightForWidth(self.toolDock.sizePolicy().hasHeightForWidth())
        self.toolDock.setSizePolicy(sizePolicy)
        self.toolDock.setMinimumSize(QSize(150, 659))
        self.toolDock.setMaximumSize(QSize(150, 659))
        self.toolDock.setBaseSize(QSize(150, 659))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolDock.setFont(font)
        self.toolDock.setStyleSheet(u"background-color: \"#A9A9A9\";")
        self.toolDock.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.toolDock.setAllowedAreas(Qt.LeftDockWidgetArea)
        self.toolDockContents = QWidget()
        self.toolDockContents.setObjectName(u"toolDockContents")
        self.toolsLabel = QLabel(self.toolDockContents)
        self.toolsLabel.setObjectName(u"toolsLabel")
        self.toolsLabel.setGeometry(QRect(20, 10, 111, 16))
        self.vertexTool = QRadioButton(self.toolDockContents)
        self.vertexTool.setObjectName(u"vertexTool")
        self.vertexTool.setGeometry(QRect(10, 40, 91, 19))
        self.paintTool = QRadioButton(self.toolDockContents)
        self.paintTool.setObjectName(u"paintTool")
        self.paintTool.setGeometry(QRect(10, 70, 91, 19))
        self.clearGraphicsButton = QPushButton(self.toolDockContents)
        self.clearGraphicsButton.setObjectName(u"clearGraphicsButton")
        self.clearGraphicsButton.setGeometry(QRect(10, 530, 81, 21))
        self.clearGraphicsButton.setStyleSheet(u"color: black; border: 1px solid black;")
        self.clearDrawingButton = QPushButton(self.toolDockContents)
        self.clearDrawingButton.setObjectName(u"clearDrawingButton")
        self.clearDrawingButton.setGeometry(QRect(10, 560, 81, 21))
        self.clearDrawingButton.setMaximumSize(QSize(149, 16777215))
        self.clearDrawingButton.setStyleSheet(u"color: black; border: 1px solid black;")
        self.toolDockTabWidget = QTabWidget(self.toolDockContents)
        self.toolDockTabWidget.setObjectName(u"toolDockTabWidget")
        self.toolDockTabWidget.setGeometry(QRect(10, 100, 127, 411))
        self.toolDockTabWidget.setStyleSheet(u"QTabWidget {\n"
"	color: rgb(135, 206, 235);\n"
"	background-color: grey;\n"
"}\n"
"\n"
"/*QSlider::handle {\n"
"	background-color: red;\n"
"}*/\n"
"/*QSlider::groove:horizontal {\n"
"	background-color: red;\n"
"}*/\n"
"QSlider::handle:horizontal {\n"
"	background-color: black;\n"
"	color: white;\n"
"}")
        self.penTab = QWidget()
        self.penTab.setObjectName(u"penTab")
        self.penAlphaSlider = QSlider(self.penTab)
        self.penAlphaSlider.setObjectName(u"penAlphaSlider")
        self.penAlphaSlider.setGeometry(QRect(10, 170, 101, 16))
        self.penAlphaSlider.setMaximum(255)
        self.penAlphaSlider.setOrientation(Qt.Horizontal)
        self.penAlphaSliderLabel = QLabel(self.penTab)
        self.penAlphaSliderLabel.setObjectName(u"penAlphaSliderLabel")
        self.penAlphaSliderLabel.setGeometry(QRect(10, 150, 91, 16))
        font1 = QFont()
        font1.setPointSize(10)
        self.penAlphaSliderLabel.setFont(font1)
        self.penSizeSlider = QSlider(self.penTab)
        self.penSizeSlider.setObjectName(u"penSizeSlider")
        self.penSizeSlider.setGeometry(QRect(10, 210, 101, 16))
        self.penSizeSlider.setMaximum(100)
        self.penSizeSlider.setOrientation(Qt.Horizontal)
        self.penSizeSliderLabel = QLabel(self.penTab)
        self.penSizeSliderLabel.setObjectName(u"penSizeSliderLabel")
        self.penSizeSliderLabel.setGeometry(QRect(10, 190, 91, 16))
        self.penSizeSliderLabel.setFont(font1)
        self.penColorLabel = QLabel(self.penTab)
        self.penColorLabel.setObjectName(u"penColorLabel")
        self.penColorLabel.setGeometry(QRect(10, 10, 47, 13))
        self.penColorLabel.setFont(font1)
        self.penGreenSliderLabel = QLabel(self.penTab)
        self.penGreenSliderLabel.setObjectName(u"penGreenSliderLabel")
        self.penGreenSliderLabel.setGeometry(QRect(10, 70, 61, 16))
        self.penGreenSliderLabel.setFont(font1)
        self.penRedSlider = QSlider(self.penTab)
        self.penRedSlider.setObjectName(u"penRedSlider")
        self.penRedSlider.setGeometry(QRect(10, 50, 101, 16))
        self.penRedSlider.setMaximum(255)
        self.penRedSlider.setOrientation(Qt.Horizontal)
        self.penGreenSlider = QSlider(self.penTab)
        self.penGreenSlider.setObjectName(u"penGreenSlider")
        self.penGreenSlider.setGeometry(QRect(10, 90, 101, 16))
        self.penGreenSlider.setMaximum(255)
        self.penGreenSlider.setOrientation(Qt.Horizontal)
        self.penBlueSliderLabel = QLabel(self.penTab)
        self.penBlueSliderLabel.setObjectName(u"penBlueSliderLabel")
        self.penBlueSliderLabel.setGeometry(QRect(10, 110, 61, 16))
        self.penBlueSliderLabel.setFont(font1)
        self.penBlueSlider = QSlider(self.penTab)
        self.penBlueSlider.setObjectName(u"penBlueSlider")
        self.penBlueSlider.setGeometry(QRect(10, 130, 101, 16))
        self.penBlueSlider.setMaximum(255)
        self.penBlueSlider.setOrientation(Qt.Horizontal)
        self.penLineStyleComboBoxLabel = QLabel(self.penTab)
        self.penLineStyleComboBoxLabel.setObjectName(u"penLineStyleComboBoxLabel")
        self.penLineStyleComboBoxLabel.setGeometry(QRect(10, 230, 71, 16))
        self.penLineStyleComboBoxLabel.setFont(font1)
        self.penLineStyleComboBox = QComboBox(self.penTab)
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.setObjectName(u"penLineStyleComboBox")
        self.penLineStyleComboBox.setGeometry(QRect(10, 250, 101, 22))
        self.penRedSliderLabel = QLabel(self.penTab)
        self.penRedSliderLabel.setObjectName(u"penRedSliderLabel")
        self.penRedSliderLabel.setGeometry(QRect(10, 30, 61, 16))
        self.penRedSliderLabel.setFont(font1)
        self.penColorSquare = QLabel(self.penTab)
        self.penColorSquare.setObjectName(u"penColorSquare")
        self.penColorSquare.setGeometry(QRect(70, 10, 31, 31))
        self.penColorSquare.setStyleSheet(u"background-color: black")
        self.toolDockTabWidget.addTab(self.penTab, "")
        self.brushTab = QWidget()
        self.brushTab.setObjectName(u"brushTab")
        self.brushAlphaSlider = QSlider(self.brushTab)
        self.brushAlphaSlider.setObjectName(u"brushAlphaSlider")
        self.brushAlphaSlider.setGeometry(QRect(10, 170, 101, 16))
        self.brushAlphaSlider.setMaximum(255)
        self.brushAlphaSlider.setOrientation(Qt.Horizontal)
        self.brushGreenSliderLabel = QLabel(self.brushTab)
        self.brushGreenSliderLabel.setObjectName(u"brushGreenSliderLabel")
        self.brushGreenSliderLabel.setGeometry(QRect(10, 70, 61, 16))
        self.brushGreenSliderLabel.setFont(font1)
        self.brushRedSlider = QSlider(self.brushTab)
        self.brushRedSlider.setObjectName(u"brushRedSlider")
        self.brushRedSlider.setGeometry(QRect(10, 50, 101, 16))
        self.brushRedSlider.setMaximum(255)
        self.brushRedSlider.setOrientation(Qt.Horizontal)
        self.brushColorLabel = QLabel(self.brushTab)
        self.brushColorLabel.setObjectName(u"brushColorLabel")
        self.brushColorLabel.setGeometry(QRect(10, 10, 47, 13))
        self.brushColorLabel.setFont(font1)
        self.brushBlueSlider = QSlider(self.brushTab)
        self.brushBlueSlider.setObjectName(u"brushBlueSlider")
        self.brushBlueSlider.setGeometry(QRect(10, 130, 101, 16))
        self.brushBlueSlider.setMaximum(255)
        self.brushBlueSlider.setOrientation(Qt.Horizontal)
        self.brushBlueSliderLabel = QLabel(self.brushTab)
        self.brushBlueSliderLabel.setObjectName(u"brushBlueSliderLabel")
        self.brushBlueSliderLabel.setGeometry(QRect(10, 110, 61, 16))
        self.brushBlueSliderLabel.setFont(font1)
        self.brushGreenSlider = QSlider(self.brushTab)
        self.brushGreenSlider.setObjectName(u"brushGreenSlider")
        self.brushGreenSlider.setGeometry(QRect(10, 90, 101, 16))
        self.brushGreenSlider.setMaximum(255)
        self.brushGreenSlider.setOrientation(Qt.Horizontal)
        self.brushRedSliderLabel = QLabel(self.brushTab)
        self.brushRedSliderLabel.setObjectName(u"brushRedSliderLabel")
        self.brushRedSliderLabel.setGeometry(QRect(10, 30, 61, 16))
        self.brushRedSliderLabel.setFont(font1)
        self.brushAlphaSliderLabel = QLabel(self.brushTab)
        self.brushAlphaSliderLabel.setObjectName(u"brushAlphaSliderLabel")
        self.brushAlphaSliderLabel.setGeometry(QRect(10, 150, 91, 16))
        self.brushAlphaSliderLabel.setFont(font1)
        self.brushColorSquare = QLabel(self.brushTab)
        self.brushColorSquare.setObjectName(u"brushColorSquare")
        self.brushColorSquare.setGeometry(QRect(70, 10, 31, 31))
        self.brushColorSquare.setStyleSheet(u"background-color: black")
        self.brushTextureComboBoxLabel = QLabel(self.brushTab)
        self.brushTextureComboBoxLabel.setObjectName(u"brushTextureComboBoxLabel")
        self.brushTextureComboBoxLabel.setGeometry(QRect(10, 190, 71, 16))
        self.brushTextureComboBoxLabel.setFont(font1)
        self.brushTextureComboBox = QComboBox(self.brushTab)
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.addItem("")
        self.brushTextureComboBox.setObjectName(u"brushTextureComboBox")
        self.brushTextureComboBox.setGeometry(QRect(10, 210, 101, 22))
        self.toolDockTabWidget.addTab(self.brushTab, "")
        self.toolDock.setWidget(self.toolDockContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.toolDock)

        self.retranslateUi(MainWindow)

        self.toolDockTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.toolsLabel.setText(QCoreApplication.translate("MainWindow", u"Tools (Exclusive)", None))
        self.vertexTool.setText(QCoreApplication.translate("MainWindow", u"Vertex", None))
        self.paintTool.setText(QCoreApplication.translate("MainWindow", u"Paint / Draw", None))
        self.clearGraphicsButton.setText(QCoreApplication.translate("MainWindow", u"Clear Graphics", None))
        self.clearDrawingButton.setText(QCoreApplication.translate("MainWindow", u"Clear Drawing", None))
        self.penAlphaSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Alpha / Opacity", None))
        self.penSizeSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Size / Width", None))
        self.penColorLabel.setText(QCoreApplication.translate("MainWindow", u"Color(s)", None))
        self.penGreenSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.penBlueSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.penLineStyleComboBoxLabel.setText(QCoreApplication.translate("MainWindow", u"Line Style", None))
        self.penLineStyleComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Solid", None))
        self.penLineStyleComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Dash", None))
        self.penLineStyleComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Dotted", None))
        self.penLineStyleComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"DashDot", None))
        self.penLineStyleComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"DashDotDot", None))

        self.penRedSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.penColorSquare.setText("")
        self.toolDockTabWidget.setTabText(self.toolDockTabWidget.indexOf(self.penTab), QCoreApplication.translate("MainWindow", u"Pen", None))
        self.brushGreenSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.brushColorLabel.setText(QCoreApplication.translate("MainWindow", u"Color(s)", None))
        self.brushBlueSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.brushRedSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.brushAlphaSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Alpha / Opacity", None))
        self.brushColorSquare.setText("")
        self.brushTextureComboBoxLabel.setText(QCoreApplication.translate("MainWindow", u"Texture", None))
        self.brushTextureComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Solid", None))
        self.brushTextureComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Dense1", None))
        self.brushTextureComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Dense2", None))
        self.brushTextureComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Dense3", None))
        self.brushTextureComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"Dense4", None))
        self.brushTextureComboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"Dense5", None))
        self.brushTextureComboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"Dense6", None))
        self.brushTextureComboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"Dense7", None))
        self.brushTextureComboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"Horizontal", None))
        self.brushTextureComboBox.setItemText(9, QCoreApplication.translate("MainWindow", u"Vertical", None))
        self.brushTextureComboBox.setItemText(10, QCoreApplication.translate("MainWindow", u"Cross", None))
        self.brushTextureComboBox.setItemText(11, QCoreApplication.translate("MainWindow", u"Diagonal1", None))
        self.brushTextureComboBox.setItemText(12, QCoreApplication.translate("MainWindow", u"Diagonal2", None))
        self.brushTextureComboBox.setItemText(13, QCoreApplication.translate("MainWindow", u"DiagCross", None))

        self.toolDockTabWidget.setTabText(self.toolDockTabWidget.indexOf(self.brushTab), QCoreApplication.translate("MainWindow", u"Brush", None))
    # retranslateUi

