# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1280, 720))
        MainWindow.setMaximumSize(QSize(1280, 720))
        MainWindow.setBaseSize(QSize(1280, 720))
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setStyleSheet(u"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 20))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        self.menuDocs = QMenu(self.menubar)
        self.menuDocs.setObjectName(u"menuDocs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolDock = QDockWidget(MainWindow)
        self.toolDock.setObjectName(u"toolDock")
        sizePolicy.setHeightForWidth(self.toolDock.sizePolicy().hasHeightForWidth())
        self.toolDock.setSizePolicy(sizePolicy)
        self.toolDock.setMinimumSize(QSize(150, 675))
        self.toolDock.setMaximumSize(QSize(150, 675))
        self.toolDock.setBaseSize(QSize(150, 675))
        self.toolDock.setStyleSheet(u"background-color: \"#A9A9A9\";")
        self.toolDock.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.toolDock.setAllowedAreas(Qt.LeftDockWidgetArea)
        self.toolDockContents = QWidget()
        self.toolDockContents.setObjectName(u"toolDockContents")
        self.toolsLabel = QLabel(self.toolDockContents)
        self.toolsLabel.setObjectName(u"toolsLabel")
        self.toolsLabel.setGeometry(QRect(20, 10, 111, 16))
        self.vertexTool = QRadioButton(self.toolDockContents)
        self.vertexTool.setObjectName(u"vertexTool")
        self.vertexTool.setGeometry(QRect(10, 40, 91, 19))
        self.paintTool = QRadioButton(self.toolDockContents)
        self.paintTool.setObjectName(u"paintTool")
        self.paintTool.setGeometry(QRect(10, 70, 91, 19))
        self.eraserTool = QRadioButton(self.toolDockContents)
        self.eraserTool.setObjectName(u"eraserTool")
        self.eraserTool.setGeometry(QRect(10, 100, 91, 19))
        self.clearGraphicsButton = QPushButton(self.toolDockContents)
        self.clearGraphicsButton.setObjectName(u"clearGraphicsButton")
        self.clearGraphicsButton.setGeometry(QRect(10, 560, 81, 21))
        self.clearGraphicsButton.setStyleSheet(u"background: grey")
        self.clearDrawingButton = QPushButton(self.toolDockContents)
        self.clearDrawingButton.setObjectName(u"clearDrawingButton")
        self.clearDrawingButton.setGeometry(QRect(10, 590, 81, 21))
        self.clearDrawingButton.setMaximumSize(QSize(149, 16777215))
        self.clearDrawingButton.setStyleSheet(u"background: grey")
        self.toolDockTabWidget = QTabWidget(self.toolDockContents)
        self.toolDockTabWidget.setObjectName(u"toolDockTabWidget")
        self.toolDockTabWidget.setGeometry(QRect(10, 130, 127, 411))
        self.penTab = QWidget()
        self.penTab.setObjectName(u"penTab")
        self.penAlphaSlider = QSlider(self.penTab)
        self.penAlphaSlider.setObjectName(u"penAlphaSlider")
        self.penAlphaSlider.setGeometry(QRect(10, 170, 91, 16))
        self.penAlphaSlider.setMaximum(255)
        self.penAlphaSlider.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.penTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 150, 91, 16))
        self.penSizeSlider = QSlider(self.penTab)
        self.penSizeSlider.setObjectName(u"penSizeSlider")
        self.penSizeSlider.setGeometry(QRect(10, 210, 91, 16))
        self.penSizeSlider.setMaximum(100)
        self.penSizeSlider.setOrientation(Qt.Horizontal)
        self.label_2 = QLabel(self.penTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 190, 61, 16))
        self.label_3 = QLabel(self.penTab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 47, 13))
        self.label_4 = QLabel(self.penTab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 70, 61, 16))
        self.penRedSlider = QSlider(self.penTab)
        self.penRedSlider.setObjectName(u"penRedSlider")
        self.penRedSlider.setGeometry(QRect(10, 50, 91, 16))
        self.penRedSlider.setMaximum(255)
        self.penRedSlider.setOrientation(Qt.Horizontal)
        self.label_5 = QLabel(self.penTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 47, 13))
        self.penGreenSlider = QSlider(self.penTab)
        self.penGreenSlider.setObjectName(u"penGreenSlider")
        self.penGreenSlider.setGeometry(QRect(10, 90, 91, 16))
        self.penGreenSlider.setMaximum(255)
        self.penGreenSlider.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.penTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 110, 61, 16))
        self.penBlueSlider = QSlider(self.penTab)
        self.penBlueSlider.setObjectName(u"penBlueSlider")
        self.penBlueSlider.setGeometry(QRect(10, 130, 91, 16))
        self.penBlueSlider.setMaximum(255)
        self.penBlueSlider.setOrientation(Qt.Horizontal)
        self.label_7 = QLabel(self.penTab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 230, 71, 16))
        self.penLineStyleComboBox = QComboBox(self.penTab)
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.addItem("")
        self.penLineStyleComboBox.setObjectName(u"penLineStyleComboBox")
        self.penLineStyleComboBox.setGeometry(QRect(10, 250, 72, 22))
        self.toolDockTabWidget.addTab(self.penTab, "")
        self.brushTab = QWidget()
        self.brushTab.setObjectName(u"brushTab")
        self.toolDockTabWidget.addTab(self.brushTab, "")
        self.toolDock.setWidget(self.toolDockContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.toolDock)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuDocs.menuAction())

        self.retranslateUi(MainWindow)

        self.toolDockTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuDocs.setTitle(QCoreApplication.translate("MainWindow", u"Docs", None))
        self.toolsLabel.setText(QCoreApplication.translate("MainWindow", u"Tools (Exclusive)", None))
        self.vertexTool.setText(QCoreApplication.translate("MainWindow", u"Vertex", None))
        self.paintTool.setText(QCoreApplication.translate("MainWindow", u"Paint / Draw", None))
        self.eraserTool.setText(QCoreApplication.translate("MainWindow", u"Eraser", None))
        self.clearGraphicsButton.setText(QCoreApplication.translate("MainWindow", u"Clear Graphics", None))
        self.clearDrawingButton.setText(QCoreApplication.translate("MainWindow", u"Clear Drawing", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Alpha / Opacity", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Size / Width", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Color(s)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Line Style", None))
        self.penLineStyleComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Solid", None))
        self.penLineStyleComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Dotted", None))

        self.toolDockTabWidget.setTabText(self.toolDockTabWidget.indexOf(self.penTab), QCoreApplication.translate("MainWindow", u"Pen", None))
        self.toolDockTabWidget.setTabText(self.toolDockTabWidget.indexOf(self.brushTab), QCoreApplication.translate("MainWindow", u"Brush", None))
    # retranslateUi

